-- MySQL Script generated by MySQL Workbench
-- Sat Mar 21 19:30:32 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering


-- -----------------------------------------------------
-- Schema shoppingdb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema shoppingdb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `shoppingdb` DEFAULT CHARACTER SET utf8 ;
USE `shoppingdb` ;

-- -----------------------------------------------------
-- Table `shoppingdb`.`person_table`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shoppingdb`.`person_table` (
  `personID` VARCHAR(255) NOT NULL,
  `firstName` VARCHAR(45) NULL,
  `lastName` VARCHAR(45) NULL,
  PRIMARY KEY (`personID`),
  UNIQUE INDEX `personID_UNIQUE` (`personID` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shoppingdb`.`user_table`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shoppingdb`.`user_table` (
  `userName` VARCHAR(255) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `usertype` VARCHAR(45) NULL,
  `personID` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`personID`),
  CONSTRAINT `fk_user_table_person_table1`
    FOREIGN KEY (`personID`)
    REFERENCES `shoppingdb`.`person_table` (`personID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shoppingdb`.`email_table`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shoppingdb`.`email_table` (
  `emailID` VARCHAR(255) NOT NULL,
  `email_address` VARCHAR(255) NULL,
  `personID` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`emailID`),
  UNIQUE INDEX `emailID_UNIQUE` (`emailID` ASC) VISIBLE,
  INDEX `fk_email_table_user_table1_idx` (`personID` ASC) VISIBLE,
  CONSTRAINT `fk_email_table_user_table1`
    FOREIGN KEY (`personID`)
    REFERENCES `shoppingdb`.`user_table` (`personID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shoppingdb`.`advert_table`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shoppingdb`.`advert_table` (
  `advertID` VARCHAR(255) NOT NULL,
  `title` VARCHAR(45) NULL,
  `message` VARCHAR(45) NULL,
  `filename` VARCHAR(45) NULL,
  `price` INT NULL,
  `personID` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`advertID`),
  UNIQUE INDEX `advertID_UNIQUE` (`advertID` ASC) VISIBLE,
  INDEX `fk_advert_table_user_table1_idx` (`personID` ASC) VISIBLE,
  CONSTRAINT `fk_advert_table_user_table1`
    FOREIGN KEY (`personID`)
    REFERENCES `shoppingdb`.`user_table` (`personID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shoppingdb`.`cart_table`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shoppingdb`.`cart_table` (
  `cartID` VARCHAR(255) NOT NULL,
  `title` VARCHAR(45) NULL,
  `category` VARCHAR(45) NULL,
  `filename` VARCHAR(45) NULL,
  `totalprice` VARCHAR(45) NULL,
  `personID` VARCHAR(255) NOT NULL,
  UNIQUE INDEX `cartID_UNIQUE` (`cartID` ASC) VISIBLE,
  PRIMARY KEY (`cartID`),
  INDEX `fk_cart_table_user_table1_idx` (`personID` ASC) VISIBLE,
  CONSTRAINT `fk_cart_table_user_table1`
    FOREIGN KEY (`personID`)
    REFERENCES `shoppingdb`.`user_table` (`personID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shoppingdb`.`cart_advert_table`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shoppingdb`.`cart_advert_table` (
  `advert_table_advertID` VARCHAR(255) NOT NULL,
  `cart_table_cartID` VARCHAR(255) NOT NULL,
  `id` VARCHAR(255) NOT NULL,
  INDEX `fk_cart_advert_table_advert_table1_idx` (`advert_table_advertID` ASC) VISIBLE,
  INDEX `fk_cart_advert_table_cart_table1_idx` (`cart_table_cartID` ASC) VISIBLE,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_cart_advert_table_advert_table1`
    FOREIGN KEY (`advert_table_advertID`)
    REFERENCES `shoppingdb`.`advert_table` (`advertID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cart_advert_table_cart_table1`
    FOREIGN KEY (`cart_table_cartID`)
    REFERENCES `shoppingdb`.`cart_table` (`cartID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shoppingdb`.`category_table`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shoppingdb`.`category_table` (
  `categoryID` VARCHAR(255) NOT NULL,
  `title` VARCHAR(45) NOT NULL,
  UNIQUE INDEX `categoryID_UNIQUE` (`categoryID` ASC) VISIBLE,
  PRIMARY KEY (`categoryID`),
  UNIQUE INDEX `title_UNIQUE` (`title` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shoppingdb`.`category_advert_table`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shoppingdb`.`category_advert_table` (
  `advert_table_advertID` VARCHAR(255) NOT NULL,
  `category_table_categoryID` VARCHAR(255) NOT NULL,
  `id` VARCHAR(255) NOT NULL,
  INDEX `fk_category_advert_table_advert_table1_idx` (`advert_table_advertID` ASC) VISIBLE,
  INDEX `fk_category_advert_table_category_table1_idx` (`category_table_categoryID` ASC) VISIBLE,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_category_advert_table_advert_table1`
    FOREIGN KEY (`advert_table_advertID`)
    REFERENCES `shoppingdb`.`advert_table` (`advertID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_category_advert_table_category_table1`
    FOREIGN KEY (`category_table_categoryID`)
    REFERENCES `shoppingdb`.`category_table` (`categoryID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

